### ISSUE TITLE
App crash when trying to edit controls overlay

### ISSUE THREAD

**Issue by Dylan96** [MiRO92/uYou-for-YouTube#82]
If you tap on "Video Controls Overlay" the app crashes.  

Youtube: 16.45.4
uYou: 2.1

**Comment by dayanch96** [comment]
Sideloaded uYou 2.1 doesn’t support this version. Latest supported version is 16.42.3.

**Comment by Macleykun** [comment]
@MiRO92 is it possible to have a look at this? This sadly makes most options inaccessible.

**Comment by dayanch96** [comment]
> @MiRO92 is it possible to have a look at this? This sadly makes most options inaccessible.

These errors have been automatically fixed in the latest versions of YouTube. Now everything works

**Comment by Arebstar** [comment]
> > @MiRO92 is it possible to have a look at this? This sadly makes most options inaccessible.
> 
> These errors have been automatically fixed in the latest versions of YouTube. Now everything works

My app still crashes when opening these settings. How do I go about updating the “latest version of YouTube”?

**Comment by dayanch96** [comment]
> > > @MiRO92 is it possible to have a look at this? This sadly makes most options inaccessible.
> > 
> > 
> > These errors have been automatically fixed in the latest versions of YouTube. Now everything works
> 
> My app still crashes when opening these settings. How do I go about updating the “latest version of YouTube”?

Not sure, bc dont know which mod you’re using. I can share with you my one which works without crashes and show video duration properly in history:
https://appdb.to/app/cydia/998720856
